spring:
  datasource:
    url: jdbc:h2:mem:trip
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---
#spring:
#  security:
#    user:
#      name: root
#      password: root
#    basic:
#      enabled: false